// Code generated by protoc-gen-go. DO NOT EDIT.
// source: publish.proto

package publish

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrCode int32

const (
	ErrCode_ErrOK            ErrCode = 0
	ErrCode_ErrNoSubScribers ErrCode = 1
	ErrCode_ErrInternalError ErrCode = 2
)

var ErrCode_name = map[int32]string{
	0: "ErrOK",
	1: "ErrNoSubScribers",
	2: "ErrInternalError",
}

var ErrCode_value = map[string]int32{
	"ErrOK":            0,
	"ErrNoSubScribers": 1,
	"ErrInternalError": 2,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}

func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{0}
}

type Target struct {
	Topic    string `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Qos      int32  `protobuf:"varint,4,opt,name=Qos,proto3" json:"Qos,omitempty"`
	IsRetain bool   `protobuf:"varint,5,opt,name=IsRetain,proto3" json:"IsRetain,omitempty"`
	// fase:  bifrost can drop this message if necessary
	// true:  bifrost will send this message to all clients that
	//        subscribed this topic.
	// Note: if set the NoneDowngrade to true, the corresponding message
	// might block the later message(when too many clients subscribed
	// this topic)
	NoneDowngrade        bool     `protobuf:"varint,6,opt,name=NoneDowngrade,proto3" json:"NoneDowngrade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{0}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Target) GetQos() int32 {
	if m != nil {
		return m.Qos
	}
	return 0
}

func (m *Target) GetIsRetain() bool {
	if m != nil {
		return m.IsRetain
	}
	return false
}

func (m *Target) GetNoneDowngrade() bool {
	if m != nil {
		return m.NoneDowngrade
	}
	return false
}

type PublishRequest struct {
	MessageID            []byte    `protobuf:"bytes,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	Payload              []byte    `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Targets              []*Target `protobuf:"bytes,3,rep,name=Targets,proto3" json:"Targets,omitempty"`
	Weight               int32     `protobuf:"varint,4,opt,name=Weight,proto3" json:"Weight,omitempty"`
	StatLabel            string    `protobuf:"bytes,5,opt,name=StatLabel,proto3" json:"StatLabel,omitempty"`
	TTL                  int32     `protobuf:"varint,6,opt,name=TTL,proto3" json:"TTL,omitempty"`
	AppKey               string    `protobuf:"bytes,7,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	Cookie               []byte    `protobuf:"bytes,8,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{1}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetMessageID() []byte {
	if m != nil {
		return m.MessageID
	}
	return nil
}

func (m *PublishRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PublishRequest) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *PublishRequest) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *PublishRequest) GetStatLabel() string {
	if m != nil {
		return m.StatLabel
	}
	return ""
}

func (m *PublishRequest) GetTTL() int32 {
	if m != nil {
		return m.TTL
	}
	return 0
}

func (m *PublishRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *PublishRequest) GetCookie() []byte {
	if m != nil {
		return m.Cookie
	}
	return nil
}

type PublishReply struct {
	ReturnCode           ErrCode   `protobuf:"varint,1,opt,name=ReturnCode,proto3,enum=publish.ErrCode" json:"ReturnCode,omitempty"`
	Results              []ErrCode `protobuf:"varint,2,rep,packed,name=Results,proto3,enum=publish.ErrCode" json:"Results,omitempty"`
	Cursor               [][]byte  `protobuf:"bytes,3,rep,name=Cursor,proto3" json:"Cursor,omitempty"`
	Cookie               []byte    `protobuf:"bytes,4,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PublishReply) Reset()         { *m = PublishReply{} }
func (m *PublishReply) String() string { return proto.CompactTextString(m) }
func (*PublishReply) ProtoMessage()    {}
func (*PublishReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{2}
}

func (m *PublishReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishReply.Unmarshal(m, b)
}
func (m *PublishReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishReply.Marshal(b, m, deterministic)
}
func (m *PublishReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishReply.Merge(m, src)
}
func (m *PublishReply) XXX_Size() int {
	return xxx_messageInfo_PublishReply.Size(m)
}
func (m *PublishReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishReply.DiscardUnknown(m)
}

var xxx_messageInfo_PublishReply proto.InternalMessageInfo

func (m *PublishReply) GetReturnCode() ErrCode {
	if m != nil {
		return m.ReturnCode
	}
	return ErrCode_ErrOK
}

func (m *PublishReply) GetResults() []ErrCode {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *PublishReply) GetCursor() [][]byte {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func (m *PublishReply) GetCookie() []byte {
	if m != nil {
		return m.Cookie
	}
	return nil
}

type DeleteQueueRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteQueueRequest) Reset()         { *m = DeleteQueueRequest{} }
func (m *DeleteQueueRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteQueueRequest) ProtoMessage()    {}
func (*DeleteQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{3}
}

func (m *DeleteQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteQueueRequest.Unmarshal(m, b)
}
func (m *DeleteQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteQueueRequest.Marshal(b, m, deterministic)
}
func (m *DeleteQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteQueueRequest.Merge(m, src)
}
func (m *DeleteQueueRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteQueueRequest.Size(m)
}
func (m *DeleteQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteQueueRequest proto.InternalMessageInfo

func (m *DeleteQueueRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type DeleteQueueReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteQueueReply) Reset()         { *m = DeleteQueueReply{} }
func (m *DeleteQueueReply) String() string { return proto.CompactTextString(m) }
func (*DeleteQueueReply) ProtoMessage()    {}
func (*DeleteQueueReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_34180b7635741fb2, []int{4}
}

func (m *DeleteQueueReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteQueueReply.Unmarshal(m, b)
}
func (m *DeleteQueueReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteQueueReply.Marshal(b, m, deterministic)
}
func (m *DeleteQueueReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteQueueReply.Merge(m, src)
}
func (m *DeleteQueueReply) XXX_Size() int {
	return xxx_messageInfo_DeleteQueueReply.Size(m)
}
func (m *DeleteQueueReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteQueueReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteQueueReply proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("publish.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterType((*Target)(nil), "publish.Target")
	proto.RegisterType((*PublishRequest)(nil), "publish.PublishRequest")
	proto.RegisterType((*PublishReply)(nil), "publish.PublishReply")
	proto.RegisterType((*DeleteQueueRequest)(nil), "publish.DeleteQueueRequest")
	proto.RegisterType((*DeleteQueueReply)(nil), "publish.DeleteQueueReply")
}

func init() { proto.RegisterFile("publish.proto", fileDescriptor_34180b7635741fb2) }

var fileDescriptor_34180b7635741fb2 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xeb, 0xa6, 0x8e, 0x93, 0xe9, 0x1f, 0xac, 0x51, 0x81, 0x25, 0x70, 0xb0, 0x2c, 0x0e,
	0x21, 0x87, 0x0a, 0x85, 0x23, 0x17, 0x50, 0x13, 0xa1, 0xa8, 0xa5, 0xb4, 0x9b, 0x48, 0x9c, 0xed,
	0x64, 0x94, 0x5a, 0x58, 0x5e, 0x33, 0xbb, 0x06, 0xf9, 0x8b, 0x70, 0xe2, 0x1b, 0xf2, 0x25, 0x90,
	0x37, 0xb6, 0x93, 0xa8, 0xb9, 0xed, 0x7b, 0xf3, 0xb4, 0xfb, 0x7b, 0xc9, 0x18, 0xce, 0xf3, 0x22,
	0x4e, 0x13, 0xfd, 0x78, 0x95, 0xb3, 0x32, 0x0a, 0xbd, 0x5a, 0x86, 0x0c, 0xdd, 0x45, 0xc4, 0x6b,
	0x32, 0x78, 0x09, 0xee, 0x42, 0xe5, 0xc9, 0x52, 0x38, 0x81, 0x33, 0xec, 0xcb, 0x8d, 0x40, 0x1f,
	0x3a, 0x0f, 0x4a, 0x8b, 0x93, 0xc0, 0x19, 0xba, 0xb2, 0x3a, 0xe2, 0x00, 0x7a, 0x33, 0x2d, 0xc9,
	0x44, 0x49, 0x26, 0xdc, 0xc0, 0x19, 0xf6, 0x64, 0xab, 0xf1, 0x2d, 0x9c, 0xdf, 0xa9, 0x8c, 0x26,
	0xea, 0x77, 0xb6, 0xe6, 0x68, 0x45, 0xa2, 0x6b, 0x03, 0xfb, 0x66, 0xf8, 0xcf, 0x81, 0x8b, 0xfb,
	0xcd, 0xfb, 0x92, 0x7e, 0x16, 0xa4, 0x0d, 0xbe, 0x81, 0xfe, 0x57, 0xd2, 0x3a, 0x5a, 0xd3, 0x6c,
	0x62, 0x01, 0xce, 0xe4, 0xd6, 0x40, 0x01, 0xde, 0x7d, 0x54, 0xa6, 0x2a, 0x5a, 0x89, 0x63, 0x3b,
	0x6b, 0x24, 0xbe, 0x03, 0x6f, 0x83, 0xaf, 0x45, 0x27, 0xe8, 0x0c, 0x4f, 0xc7, 0xcf, 0xae, 0x9a,
	0xa2, 0x1b, 0x5f, 0x36, 0x73, 0x7c, 0x01, 0xdd, 0xef, 0x94, 0xac, 0x1f, 0x4d, 0x5d, 0xa6, 0x56,
	0xd5, 0xd3, 0x73, 0x13, 0x99, 0xdb, 0x28, 0xa6, 0xd4, 0x16, 0xea, 0xcb, 0xad, 0x51, 0xf5, 0x5f,
	0x2c, 0x6e, 0x6d, 0x0f, 0x57, 0x56, 0xc7, 0xea, 0x9e, 0xcf, 0x79, 0x7e, 0x43, 0xa5, 0xf0, 0x6c,
	0xb8, 0x56, 0x95, 0x7f, 0xad, 0xd4, 0x8f, 0x84, 0x44, 0xcf, 0x32, 0xd6, 0x2a, 0xfc, 0xeb, 0xc0,
	0x59, 0xdb, 0x36, 0x4f, 0x4b, 0x7c, 0x0f, 0x20, 0xc9, 0x14, 0x9c, 0x5d, 0xab, 0x15, 0xd9, 0xb2,
	0x17, 0x63, 0xbf, 0xc5, 0x9e, 0x32, 0x57, 0xbe, 0xdc, 0xc9, 0xe0, 0x08, 0x3c, 0x49, 0xba, 0x48,
	0x8d, 0x16, 0xc7, 0x41, 0xe7, 0x60, 0xbc, 0x09, 0x58, 0x8c, 0x82, 0xb5, 0x62, 0xfb, 0x83, 0x54,
	0x18, 0x56, 0xed, 0xe0, 0x9d, 0xec, 0xe1, 0x8d, 0x00, 0x27, 0x94, 0x92, 0xa1, 0x87, 0x82, 0x0a,
	0x6a, 0xfe, 0x8f, 0x83, 0xcb, 0x10, 0x22, 0xf8, 0x7b, 0xd9, 0x3c, 0x2d, 0x47, 0x9f, 0xc0, 0xab,
	0x19, 0xb0, 0x0f, 0xee, 0x94, 0xf9, 0xdb, 0x8d, 0x7f, 0x84, 0x97, 0xe0, 0x4f, 0x99, 0xef, 0xd4,
	0xbc, 0x88, 0xe7, 0x4b, 0x4e, 0x62, 0x62, 0xed, 0x3b, 0xb5, 0x3b, 0xcb, 0x0c, 0x71, 0x16, 0xa5,
	0x53, 0x66, 0xc5, 0xfe, 0xf1, 0xf8, 0xcf, 0x76, 0x1d, 0xe6, 0xc4, 0xbf, 0x92, 0x25, 0xe1, 0x47,
	0xf0, 0x6a, 0x07, 0x5f, 0xb6, 0x55, 0xf7, 0x57, 0x66, 0xf0, 0xfc, 0xe9, 0x20, 0x4f, 0xcb, 0xf0,
	0x08, 0xbf, 0xc0, 0xe9, 0x0e, 0x25, 0xbe, 0x6e, 0x73, 0x4f, 0x7b, 0x0e, 0x5e, 0x1d, 0x1e, 0xda,
	0x8b, 0xe2, 0xae, 0xfd, 0x56, 0x3e, 0xfc, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xab, 0x7d, 0xee, 0x18,
	0x3c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PublishServiceClient is the client API for PublishService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublishServiceClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishReply, error)
	DeleteQueue(ctx context.Context, in *DeleteQueueRequest, opts ...grpc.CallOption) (*DeleteQueueReply, error)
}

type publishServiceClient struct {
	cc *grpc.ClientConn
}

func NewPublishServiceClient(cc *grpc.ClientConn) PublishServiceClient {
	return &publishServiceClient{cc}
}

func (c *publishServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishReply, error) {
	out := new(PublishReply)
	err := c.cc.Invoke(ctx, "/publish.PublishService/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publishServiceClient) DeleteQueue(ctx context.Context, in *DeleteQueueRequest, opts ...grpc.CallOption) (*DeleteQueueReply, error) {
	out := new(DeleteQueueReply)
	err := c.cc.Invoke(ctx, "/publish.PublishService/DeleteQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublishServiceServer is the server API for PublishService service.
type PublishServiceServer interface {
	Publish(context.Context, *PublishRequest) (*PublishReply, error)
	DeleteQueue(context.Context, *DeleteQueueRequest) (*DeleteQueueReply, error)
}

// UnimplementedPublishServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPublishServiceServer struct {
}

func (*UnimplementedPublishServiceServer) Publish(ctx context.Context, req *PublishRequest) (*PublishReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedPublishServiceServer) DeleteQueue(ctx context.Context, req *DeleteQueueRequest) (*DeleteQueueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQueue not implemented")
}

func RegisterPublishServiceServer(s *grpc.Server, srv PublishServiceServer) {
	s.RegisterService(&_PublishService_serviceDesc, srv)
}

func _PublishService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublishServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publish.PublishService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublishServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublishService_DeleteQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublishServiceServer).DeleteQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publish.PublishService/DeleteQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublishServiceServer).DeleteQueue(ctx, req.(*DeleteQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PublishService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "publish.PublishService",
	HandlerType: (*PublishServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _PublishService_Publish_Handler,
		},
		{
			MethodName: "DeleteQueue",
			Handler:    _PublishService_DeleteQueue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publish.proto",
}
